--TRANSFORMATION 
 SELECT A.NAME, A.ID_DIRECTORY,  B.VALUE_STR
    FROM R_TRANSFORMATION A 
   INNER JOIN R_STEP_ATTRIBUTE B
      ON A.ID_TRANSFORMATION = B.ID_TRANSFORMATION
   WHERE B.CODE = 'sql'
   ORDER BY A.ID_DIRECTORY, A.NAME ;

--JOB
SELECT J.ID_JOB, 
       J.NAME AS JOB_NAME, 
       J.ID_DIRECTORY, 
       D.ID_DIRECTORY_PARENT, 
       E.ID_JOBENTRY_TYPE, 
       E.ID_JOBENTRY, 
       A.VALUE_STR, 
       E.NAME AS SUB_NAME ,E.ID_JOBENTRY
  FROM R_JOB J
  LEFT JOIN R_DIRECTORY D 
    ON D.ID_DIRECTORY = J.ID_DIRECTORY
  LEFT JOIN R_JOBENTRY E 
    ON J.ID_JOB = E.ID_JOB
  LEFT JOIN R_JOBENTRY_ATTRIBUTE A 
    ON E.ID_JOBENTRY = A.ID_JOBENTRY
WHERE A.CODE='sql'
AND J.NAME LIKE 'R_CISP_%' ESCAPE '/'
AND UPPER(A.VALUE_STR) LIKE '%D_GETDATE%'
 AND UPPER(A.VALUE_STR) NOT LIKE '%D_GETDATE_M%'
 AND E.NAME = J.NAME
ORDER BY J.ID_DIRECTORY, J.ID_JOB ;
